name: release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      BUILD_REL_PATH: 'build-folder'
      RELEASE_REL_PATH: 'release-folder'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npx webpack --mode=production
      - run: echo # here update manifest.json
      - run: npx web-ext build
      - uses: actions/upload-artifact@2.1.0
        with:
          name: release-package
          path: extension/**/*
      - uses: actions/checkout@v2
        with:
          repository: 'colin-delhalle/webextension-builder'
          path: RELEASE_REL_PATH
      - 
      - run: mkdir strawpoll-viewer/releases/1.0.0
        working-directory: RELEASE_REL_PATH
      - run: cp -R GITHUB_WORKSPACE/BUILD_REL_PATH/extension GITHUB_WORKSPACE/RELEASE_REL_PATH/releases/1.0.0
