name: release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npx webpack --mode=production
      - run: echo 'update manifest.json' # here update manifest.json
      - run: cd extension && npx web-ext build
      - uses: actions/upload-artifact@2.1.0
        with:
          name: release-${{ github.event.release.tag_name }}
          path: extension/**/*

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2.0.5
        with:
          name: release-${{ github.event.release.tag_name }}
          path: ~/strawpoll-viewer/
      - uses: actions/checkout@v2
        with:
          repository: 'colin-delhalle/webextension-builder'
          token: ${{ secrets.PAT }}
      - run: |
          git add .
          git commit -m "Release ${{ github.event.release.tag_name }}"
          git push
