name: release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      BUILD_REL_PATH: 'build-folder'
      RELEASE_REL_PATH: 'release-folder'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - run: echo $GITHUB_REF
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npx webpack --mode=production
      - run: echo 'update manifest.json' # here update manifest.json
      - run: npx web-ext build
      - uses: actions/upload-artifact@2.1.0
        with:
          name: release-package
          path: extension/**/*
      - uses: actions/checkout@v2
        with:
          repository: 'colin-delhalle/webextension-builder'
          path: $RELEASE_REL_PATH
      - run: mkdir strawpoll-viewer/releases/$GITHUB_REF
        working-directory: $GITHUB_WORKSPACE/$RELEASE_REL_PATH
      - run: cp -R $GITHUB_WORKSPACE/$BUILD_REL_PATH/extension $GITHUB_WORKSPACE/$RELEASE_REL_PATH/releases/$GITHUB_REF
      - run: git add .
        working-directory: $GITHUB_WORKSPACE/$RELEASE_REL_PATH
      - run: git commit -m "Source and zip file for relase $GITHUB_REF"
        working-directory: $GITHUB_WORKSPACE/$RELEASE_REL_PATH
      - run: git push
        working-directory: $GITHUB_WORKSPACE/$RELEASE_REL_PATH
